# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # 1. Automatically find and update npm dependencies anywhere in the repo
  - package-ecosystem: "npm"
    directories:
      - "/**" # Tells Dependabot to find all package.json files recursively
    schedule:
      interval: "weekly"

  # 2. Automatically find and update Python dependencies anywhere in the repo
  - package-ecosystem: "pip"
    directories:
      - "/**" # Tells Dependabot to find pyproject.toml / requirements.txt recursively
    schedule:
      interval: "weekly"
